[package]
name = "spl-math"
version = "0.3.0"
description = "Solana Program Library Math"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
num-traits = "0.2"
uint = "0.10"

[dev-dependencies]
proptest = "1.5.0"
libm = "0.2.11"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
