[package]
name = "spl-transfer-hook-example"
version = "0.6.0"
description = "Solana Program Library Transfer Hook Example Program"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
default = ["forbid-additional-mints"]
no-entrypoint = []
test-sbf = []
forbid-additional-mints = []

[dependencies]
arrayref = "0.3.9"
solana-program = "2.1.0"
spl-tlv-account-resolution = { version = "0.9.0", path = "../../../libraries/tlv-account-resolution" }
spl-token-2022 = { version = "6.0.0",  path = "../../program-2022", features = ["no-entrypoint"] }
spl-transfer-hook-interface = { version = "0.9.0", path = "../interface" }
spl-type-length-value = { version = "0.7.0", path = "../../../libraries/type-length-value" }

[dev-dependencies]
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
