[package]
name = "spl-token-group-interface"
version = "0.5.0"
description = "Solana Program Library Token Group Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bytemuck = "1.20.0"
num-derive = "0.4"
num-traits = "0.2"
solana-decode-error = "2.1.0"
solana-instruction = "2.1.0"
solana-msg = "2.1.0"
solana-program-error = "2.1.0"
solana-pubkey = "2.1.0"
spl-discriminator = { version = "0.4.0", path = "../../libraries/discriminator" }
spl-pod = { version = "0.5.0", path = "../../libraries/pod", features = ["borsh"] }
thiserror = "2.0"

[dev-dependencies]
solana-sha256-hasher = "2.1.0"
spl-type-length-value = { version = "0.7.0", path = "../../libraries/type-length-value", features = ["derive"] }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
