[package]
name = "spl-type-length-value"
version = "0.7.0"
description = "Solana Program Library Type-Length-Value Management"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"
exclude = ["js/**"]

[features]
derive = ["dep:spl-type-length-value-derive"]

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
solana-account-info = "2.1.0"
solana-decode-error = "2.1.0"
solana-msg = "2.1.0"
solana-program-error = "2.1.0"
spl-discriminator = { version = "0.4.0", path = "../discriminator" }
spl-type-length-value-derive = { version = "0.1", path = "./derive", optional = true }
spl-pod = { version = "0.5.0", path = "../pod" }
thiserror = "2.0"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
