[package]
name = "spl-discriminator"
version = "0.4.0"
description = "Solana Program Library 8-Byte Discriminator Management"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
borsh = ["dep:borsh"]

[dependencies]
borsh = { version = "1", optional = true }
bytemuck = { version = "1.20.0", features = ["derive"] }
solana-program-error = "2.1.0"
solana-sha256-hasher = "2.1.0"
spl-discriminator-derive = { version = "0.2.0", path = "./derive" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
