[package]
name = "spl-transfer-hook-interface"
version = "0.9.0"
description = "Solana Program Library Transfer Hook Interface"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[dependencies]
arrayref = "0.3.9"
bytemuck = { version = "1.20.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
solana-account-info = "2.1.0"
solana-cpi = "2.1.0"
solana-decode-error = "2.1.0"
solana-instruction = { version = "2.1.0", features = ["std"] }
solana-msg = "2.1.0"
solana-program-error = "2.1.0"
solana-pubkey = { version = "2.1.0", features = ["curve25519"] }
spl-discriminator = { version = "0.4.0" , path = "../../../libraries/discriminator" }
spl-program-error = { version = "0.6.0", path = "../../../libraries/program-error" }
spl-tlv-account-resolution = { version = "0.9.0", path = "../../../libraries/tlv-account-resolution" }
spl-type-length-value = { version = "0.7.0", path = "../../../libraries/type-length-value" }
spl-pod = { version = "0.5.0", path = "../../../libraries/pod" }
thiserror = "2.0"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
solana-program = "2.1.0"
tokio = { version = "1.42.0", features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
