[package]
name = "spl-single-pool"
version = "1.0.1"
description = "Solana Program Library Single-Validator Stake Pool"
authors = ["Solana Labs Maintainers <maintainers@solanalabs.com>"]
repository = "https://github.com/solana-labs/solana-program-library"
license = "Apache-2.0"
edition = "2021"

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
arrayref = "0.3.9"
borsh = "1.5.3"
num-derive = "0.4"
num-traits = "0.2"
num_enum = "0.7.3"
solana-program = "2.1.0"
solana-security-txt = "1.1.1"
spl-token = { version = "7.0", path = "../../token/program", features = [
  "no-entrypoint",
] }
thiserror = "2.0"

[dev-dependencies]
solana-program-test = "2.1.0"
solana-sdk = "2.1.0"
solana-vote-program = "2.1.0"
spl-associated-token-account = { version = "6.0.0", path = "../../associated-token-account/program", features = [
  "no-entrypoint",
] }
spl-associated-token-account-client = { version = "2.0.0", path = "../../associated-token-account/client" }
test-case = "3.3"
bincode = "1.3.1"
rand = "0.8.5"
approx = "0.5.1"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true
