name: Pull Request JS

on:
  pull_request:
    paths:
      - 'account-compression/sdk/**'
      - 'libraries/type-length-value/js/**'
      - 'name-service/js/**'
      - 'single-pool/js/**'
      - 'stake-pool/js/**'
      - 'token/js/**'
      - 'token-group/js/**'
      - 'token-lending/js/**'
      - 'token-metadata/js/**'
      - 'token-swap/js/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/pull-request-js.yml'
  push:
    branches: [master]
    paths:
      - 'account-compression/sdk/**'
      - 'libraries/type-length-value/js/**'
      - 'single-pool/js/**'
      - 'stake-pool/js/**'
      - 'token/js/**'
      - 'token-group/js/**'
      - 'token-lending/js/**'
      - 'token-metadata/js/**'
      - 'token-swap/js/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/pull-request-js.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  js-test:
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        package:
          [
            name-service,
            stake-pool,
            token,
            token-swap,
          ]
        include:
          # Restrict certain packages to supported Node.js versions.
          - package: account-compression
            node-version: 20.x
          - package: libraries
            node-version: 20.x
          - package: single-pool
            node-version: 20.5
          - package: token-group
            node-version: 20.x
          - package: token-lending
            node-version: 18.5
          - package: token-metadata
            node-version: 20.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-
      - run: ./ci/js-test-${{ matrix.package }}.sh
